import React from 'react';

export const Disclaimer = () => {
  return (
    <div className="mt-8 p-4 bg-slate-700/50 border border-slate-600 rounded-lg text-xs text-slate-400 text-center">
      <p className="font-semibold mb-1">Important Disclaimer:</p>
      <p>
        The analysis provided by this tool is generated by an Artificial Intelligence (AI) model
        and is for informational purposes only. It should not be considered as legal advice or a
        substitute for consultation with a qualified legal professional. While we strive for accuracy,
        AI interpretations may not always be complete, error-free, or up-to-date with the latest
        legal standards or specific jurisdictional requirements. Always review policies carefully
        yourself and consult a legal expert for critical decisions.
      </p>
    </div>
  );
};
